environment:
  matrix:

    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    # Only Python 3.6+ is supported

    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

install:
  # Prepend Python installation and scripts (e.g. pytest) to PATH
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

  # Install pywin32 for Windows Events
  - "python -m pip install pywin32"

  # We need to install the python-can library itself including the dependencies
  - "python -m pip install .[test,neovi]"

build: off

test_script:
  # run tests
  - "pytest"

  # uplad coverage reports
  - "codecov -X gcov"
